export const floodPoints = [
  {
    "id": 1,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Đông Hưng Thuận",
    "street": "đường Nguyễn Văn Quá",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.8441,
    "lng": 106.6235,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 2,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Đông Hưng Thuận",
    "street": "đường Phan Văn Hớn",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.8415,
    "lng": 106.619,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 3,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thạnh Mỹ Tây",
    "street": "đường Bạch Đằng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.8038,
    "lng": 106.7021,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 4,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thạnh Mỹ Tây",
    "street": "đường Ung Văn Khiêm",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.8082,
    "lng": 106.7163,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 5,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thạnh Mỹ Tây",
    "street": "đường Đinh Bộ Lĩnh",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.812,
    "lng": 106.71,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 6,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường An Lạc",
    "street": "đường Hồ Học Lãm",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.7235,
    "lng": 106.612,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 7,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Phú Lâm",
    "street": "đường An Dương Vương",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.751,
    "lng": 106.6295,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 8,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thông Tây Hội, An Hội Đông",
    "street": "đường Lê Văn Thọ",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.8465,
    "lng": 106.657,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 9,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thông Tây Hội, An Hội Đông",
    "street": "đường Lê Đức Thọ",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.849,
    "lng": 106.671,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 10,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thông Tây Hội, An Hội Đông",
    "street": "đường Nguyễn Văn Khối",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.842,
    "lng": 106.652,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 11,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thông Tây Hội, An Hội Đông",
    "street": "đường Phan Huy Ích",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.8285,
    "lng": 106.638,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 12,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thông Tây Hội, An Hội Đông",
    "street": "đường Phạm Văn Chiêu",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.851,
    "lng": 106.645,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 13,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Đông Hưng Thuận",
    "street": "đường Phan Văn Hớn (đoạn 2)",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.843,
    "lng": 106.615,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 14,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Đông Hưng Thuận",
    "street": "đường Song hành Quốc lộ 22",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.8495,
    "lng": 106.6185,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 15,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bình Trị Đông",
    "street": "đường Phan Anh",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.768,
    "lng": 106.618,
    "note": "Lượng mưa 30mm - 50mm, mực triều < 1m"
  },
  {
    "id": 16,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Calmette",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.7685,
    "lng": 106.6995,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 17,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Phạm Viết Chánh",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.766,
    "lng": 106.685,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 18,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Đông Hưng Thuận",
    "street": "đường Nguyễn Văn Quá (đoạn 2)",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.847,
    "lng": 106.626,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 19,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Đông Hưng Thuận",
    "street": "đường Song hành Quốc lộ 22 (đoạn 2)",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.853,
    "lng": 106.616,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 20,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bình Hưng",
    "street": "đường Phạm Hùng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.738,
    "lng": 106.673,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 21,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bình Hưng",
    "street": "Quốc lộ 50",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.725,
    "lng": 106.661,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 22,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thạnh Mỹ Tây, Bình Quới",
    "street": "đường Bình Quới",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.82,
    "lng": 106.728,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 23,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thạnh Mỹ Tây, Bình Quới",
    "street": "đường D5",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.806,
    "lng": 106.714,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 24,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Thạnh Mỹ Tây, Bình Quới",
    "street": "đường Nguyễn Gia Trí",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.8035,
    "lng": 106.7155,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 25,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bình Trị Đông, Bình Hưng",
    "street": "đường Tân Hòa Đông",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.762,
    "lng": 106.624,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 26,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bình Trị Đông, Bình Hưng",
    "street": "đường Tỉnh lộ 10",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.758,
    "lng": 106.612,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 27,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bình Trị Đông, Bình Hưng",
    "street": "đường Võ Văn Kiệt",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.742,
    "lng": 106.645,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 28,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Tân Sơn Nhất",
    "street": "đường Trường Sơn",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.8145,
    "lng": 106.6625,
    "note": "Độ sâu 10cm - 15cm, nước rút < 30 phút"
  },
  {
    "id": 29,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Cống Quỳnh",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.767,
    "lng": 106.688,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 30,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Lê Lợi",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7745,
    "lng": 106.701,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 31,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Lê Thánh Tôn",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.777,
    "lng": 106.702,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 32,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Lê Thị Riêng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.771,
    "lng": 106.691,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 33,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Nguyễn Cư Trinh",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7635,
    "lng": 106.6895,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 34,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Nguyễn Trãi",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.769,
    "lng": 106.6915,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 35,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Phạm Ngũ Lão",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.768,
    "lng": 106.694,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 36,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé",
    "street": "đường Trương Định",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7755,
    "lng": 106.6935,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 37,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bàn Cờ",
    "street": "đường Nguyễn Thiện Thuật",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7695,
    "lng": 106.6815,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 38,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Khánh Hội",
    "street": "đường Hoàng Diệu",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7625,
    "lng": 106.704,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 39,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Khánh Hội",
    "street": "đường Tân Vĩnh",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7595,
    "lng": 106.703,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 40,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Khánh Hội",
    "street": "đường Tôn Thất Thuyết",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7565,
    "lng": 106.7085,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 41,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Khánh Hội",
    "street": "đường Vĩnh Hội",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7585,
    "lng": 106.705,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 42,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Khánh Hội",
    "street": "đường Xóm Chiếu",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7615,
    "lng": 106.708,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 43,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Khánh Hội",
    "street": "đường Đoàn Văn Bơ",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.761,
    "lng": 106.706,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 44,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Chợ Quán",
    "street": "đường Nguyễn Biểu",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7525,
    "lng": 106.682,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 45,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Chợ Quán",
    "street": "đường Nguyễn Văn Cừ",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.756,
    "lng": 106.683,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 46,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Chợ Quán",
    "street": "đường Trần Hưng Đạo",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.754,
    "lng": 106.679,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 47,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Diên Hồng",
    "street": "đường Lê Hồng Phong",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.769,
    "lng": 106.673,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 48,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Diên Hồng",
    "street": "đường 3/2",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.7715,
    "lng": 106.6745,
    "note": "Độ sâu < 10cm, nước rút < 30 phút"
  },
  {
    "id": 49,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bến Nghé (1 tuyến)",
    "street": "đường Calmette",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.7675,
    "lng": 106.699,
    "note": "Tuyến chịu ảnh hưởng triều cường"
  },
  {
    "id": 50,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bình Quới (1 tuyến)",
    "street": "đường Bình Quới",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.825,
    "lng": 106.732,
    "note": "Tuyến chịu ảnh hưởng triều cường"
  },
  {
    "id": 51,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Tân Thuận, Phú Thuận (2 tuyến)",
    "street": "đường Trần Xuân Soạn",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.7485,
    "lng": 106.711,
    "note": "Tuyến bờ kênh Tẻ, ảnh hưởng triều cường"
  },
  {
    "id": 52,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Tân Thuận, Phú Thuận (2 tuyến)",
    "street": "đường Huỳnh Tấn Phát",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.743,
    "lng": 106.734,
    "note": "Tuyến chịu ảnh hưởng triều cường"
  },
  {
    "id": 53,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Tân Thuận, Tân Mỹ, Nhà Bè (4 tuyến)",
    "street": "đường Lê Văn Lương",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.731,
    "lng": 106.705,
    "note": "Tuyến chịu ảnh hưởng triều cường"
  },
  {
    "id": 54,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Tân Thuận, Tân Mỹ, Nhà Bè (4 tuyến)",
    "street": "đường Đào Sư Tích",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.702,
    "lng": 106.712,
    "note": "Tuyến chịu ảnh hưởng triều cường"
  },
  {
    "id": 55,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Tân Thuận, Tân Mỹ, Nhà Bè (4 tuyến)",
    "street": "đường Phạm Hữu Lầu",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.713,
    "lng": 106.726,
    "note": "Tuyến chịu ảnh hưởng triều cường"
  },
  {
    "id": 56,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Tân Thuận, Tân Mỹ, Nhà Bè (4 tuyến)",
    "street": "đường Nguyễn Bình",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.686,
    "lng": 106.724,
    "note": "Tuyến chịu ảnh hưởng triều cường"
  },
  {
    "id": 57,
    "region": "hcm-old",
    "regionName": "TPHCM trước đây",
    "ward": "Phường Bình Hưng (1 tuyến)",
    "street": "Quốc lộ 50",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.722,
    "lng": 106.66,
    "note": "Tuyến chịu ảnh hưởng triều cường"
  },
  {
    "id": 58,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường An Khánh",
    "street": "đường Nguyễn Văn Hưởng",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.812,
    "lng": 106.734,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 59,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường An Khánh",
    "street": "đường Quốc Hương",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.804,
    "lng": 106.735,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 60,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường An Khánh",
    "street": "đường Thảo Điền",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.806,
    "lng": 106.732,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 61,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Tam Bình",
    "street": "đường Lê Thị Hoa",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.875,
    "lng": 106.741,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 62,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Tam Bình",
    "street": "đường Tỉnh lộ 43",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.879,
    "lng": 106.743,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 63,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Thủ Đức",
    "street": "đường Dương Văn Cam",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.852,
    "lng": 106.76,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 64,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Thủ Đức",
    "street": "đường Kha Vạn Cân",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.854,
    "lng": 106.762,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 65,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Thủ Đức",
    "street": "đường Tam Tam Xã",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.851,
    "lng": 106.758,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 66,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Thủ Đức",
    "street": "đường Tô Ngọc Vân",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.857,
    "lng": 106.759,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 67,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Thủ Đức",
    "street": "đường Đặng Thị Rành",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Ngập thường xuyên",
    "lat": 10.853,
    "lng": 106.7595,
    "note": "Ngập thường xuyên do mưa và triều"
  },
  {
    "id": 68,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Bình Trưng",
    "street": "đường Nguyễn Duy Trinh",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.792,
    "lng": 106.776,
    "note": "Ngập vừa do mưa và triều"
  },
  {
    "id": 69,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Hiệp Bình",
    "street": "đường Hiệp Bình",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.838,
    "lng": 106.725,
    "note": "Ngập vừa do mưa và triều"
  },
  {
    "id": 70,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Hiệp Bình",
    "street": "Quốc lộ 13",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.835,
    "lng": 106.721,
    "note": "Ngập vừa do mưa và triều"
  },
  {
    "id": 71,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Phước Long",
    "street": "đường Dương Đình Hội",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.824,
    "lng": 106.772,
    "note": "Ngập vừa do mưa và triều"
  },
  {
    "id": 72,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Phước Long",
    "street": "đường Đỗ Xuân Hợp",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.821,
    "lng": 106.776,
    "note": "Ngập vừa do mưa và triều"
  },
  {
    "id": 73,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Tam Bình",
    "street": "đường Đỗ Mười (Quốc lộ 1)",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.868,
    "lng": 106.735,
    "note": "Ngập vừa do mưa và triều"
  },
  {
    "id": 74,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Thủ Đức",
    "street": "đường Hồ Văn Tư",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.855,
    "lng": 106.764,
    "note": "Ngập vừa do mưa và triều"
  },
  {
    "id": 75,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Tăng Nhơn Phú",
    "street": "đường Lã Xuân Oai",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.839,
    "lng": 106.788,
    "note": "Ngập vừa do mưa và triều"
  },
  {
    "id": 76,
    "region": "thu-duc",
    "regionName": "TP Thủ Đức",
    "ward": "Phường Tăng Nhơn Phú",
    "street": "đường Lê Văn Việt",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.846,
    "lng": 106.782,
    "note": "Ngập nhẹ do mưa và triều"
  },
  {
    "id": 77,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thủ Dầu Một",
    "street": "đại lộ Bình Dương, đoạn trước Trường Đại học Bình Dương",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.981,
    "lng": 106.671,
    "note": "Khu vực Thủ Dầu Một (5 điểm)"
  },
  {
    "id": 78,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thủ Dầu Một",
    "street": "đường Nguyễn Văn Thành (ĐT 741)",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 11.025,
    "lng": 106.698,
    "note": "Khu vực Thủ Dầu Một (5 điểm)"
  },
  {
    "id": 79,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thủ Dầu Một",
    "street": "ngã ba đường Đoàn Trần Nghiệp - đường Hai Bà Trưng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.978,
    "lng": 106.657,
    "note": "Khu vực Thủ Dầu Một (5 điểm)"
  },
  {
    "id": 80,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thủ Dầu Một",
    "street": "đường Nguyễn Tri Phương",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.971,
    "lng": 106.662,
    "note": "Khu vực Thủ Dầu Một (5 điểm)"
  },
  {
    "id": 81,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thủ Dầu Một",
    "street": "đường Nguyễn Đức Thuận",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.992,
    "lng": 106.668,
    "note": "Khu vực Thủ Dầu Một (5 điểm)"
  },
  {
    "id": 82,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "đường số 5 tại khu dân cư Nhị Đồng 1 (chợ Bà Diệp)",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.902,
    "lng": 106.762,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 83,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "đường số 7 tại khu dân cư Nhị Đồng 1 (chợ Bà Diệp)",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.904,
    "lng": 106.764,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 84,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "đường Phạm Ngũ Lão - Phan Huy Ích",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.898,
    "lng": 106.769,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 85,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "đường An Bình tại phường An Bình",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.887,
    "lng": 106.758,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 86,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "đường Bế Văn Đàn tại phường An Bình",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.889,
    "lng": 106.7595,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 87,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "khu vực tổ 11 tại phường Hiệp Thắng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.895,
    "lng": 106.792,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 88,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "khu dân cư Tràng An",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.912,
    "lng": 106.778,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 89,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "đường ĐT 743B",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.915,
    "lng": 106.765,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 90,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "đường ĐT 747B",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.932,
    "lng": 106.781,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 91,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "mương dọc đường sắt Bắc - Nam, khu dân cư Đông Hòa",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.893,
    "lng": 106.775,
    "note": "Khu vực Dĩ An (10 điểm)"
  },
  {
    "id": 92,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đường Bùi Hữu Nghĩa",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.923,
    "lng": 106.702,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 93,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đại lộ Bình Dương (Quốc lộ 13) đoạn giáp suối Cát",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.942,
    "lng": 106.685,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 94,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đại lộ Bình Dương (Quốc lộ 13) đoạn trước Trường Dạy nghề Việt Nam - Singapore",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.931,
    "lng": 106.698,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 95,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đại lộ Bình Dương (Quốc lộ 13) đoạn trước siêu thị Lotte Thuận An",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.926,
    "lng": 106.703,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 96,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đường ĐT 743A",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.918,
    "lng": 106.721,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 97,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đường Bùi Thị Xuân",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.945,
    "lng": 106.732,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 98,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đường Lê Thị Trung",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.951,
    "lng": 106.715,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 99,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đường Thuận An Hòa",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.938,
    "lng": 106.71,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 100,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đường Thuận Giao 19",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 10.952,
    "lng": 106.708,
    "note": "Khu vực Thuận An (9 điểm)"
  },
  {
    "id": 101,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Tân Uyên",
    "street": "đường ĐT 747B",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập cục bộ",
    "lat": 11.045,
    "lng": 106.782,
    "note": "Khu vực Tân Uyên (1 điểm ngập cục bộ)"
  },
  {
    "id": 102,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "1 đoạn trên đường ĐT 741",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 11.142,
    "lng": 106.645,
    "note": "Bến Cát (19 điểm ngập)"
  },
  {
    "id": 103,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "1 đoạn trên đường ĐT 741 (đoạn 2)",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 11.146,
    "lng": 106.649,
    "note": "Bến Cát (19 điểm ngập)"
  },
  {
    "id": 104,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Đường 2-8-9",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 11.129,
    "lng": 106.608,
    "note": "Bến Cát (19 điểm ngập)"
  },
  {
    "id": 105,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13, đoạn cổng Khu công nghiệp Hoàng Gia Tân Định",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 11.082,
    "lng": 106.634,
    "note": "Bến Cát (19 điểm ngập)"
  },
  {
    "id": 106,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13, đoạn trước Trường Tiểu học Tân Định",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 11.087,
    "lng": 106.632,
    "note": "Bến Cát (19 điểm ngập)"
  },
  {
    "id": 107,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13: trước UBND phường Mỹ Phước",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.134,
    "lng": 106.612,
    "note": "7 điểm ngập cục bộ trên QL13"
  },
  {
    "id": 108,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13: trước chợ Mỹ Hạnh",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.139,
    "lng": 106.61,
    "note": "7 điểm ngập cục bộ trên QL13"
  },
  {
    "id": 109,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13: trước khu dân cư Mỹ Phước 4",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.125,
    "lng": 106.618,
    "note": "7 điểm ngập cục bộ trên QL13"
  },
  {
    "id": 110,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13: khu vực gần bến Chà Vi",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.145,
    "lng": 106.605,
    "note": "7 điểm ngập cục bộ trên QL13"
  },
  {
    "id": 111,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13: trước Nghĩa trang Liệt sĩ Bến Cát",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.118,
    "lng": 106.622,
    "note": "7 điểm ngập cục bộ trên QL13"
  },
  {
    "id": 112,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13: ngã ba cầu Suối Tre",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.152,
    "lng": 106.602,
    "note": "7 điểm ngập cục bộ trên QL13"
  },
  {
    "id": 113,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Quốc lộ 13: trước Công an thị xã Bến Cát",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.131,
    "lng": 106.614,
    "note": "7 điểm ngập cục bộ trên QL13"
  },
  {
    "id": 114,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Đường ĐT 748",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập",
    "lat": 11.155,
    "lng": 106.575,
    "note": "Bến Cát (19 điểm ngập)"
  },
  {
    "id": 115,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Đường ĐT 744: trước xã Phú An",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.112,
    "lng": 106.545,
    "note": "6 điểm ngập cục bộ trên ĐT 744"
  },
  {
    "id": 116,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Đường ĐT 744: tiệm rửa xe Minh Tâm",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.115,
    "lng": 106.542,
    "note": "6 điểm ngập cục bộ trên ĐT 744"
  },
  {
    "id": 117,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Đường ĐT 744: trước Công ty CP Greentech",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.119,
    "lng": 106.538,
    "note": "6 điểm ngập cục bộ trên ĐT 744"
  },
  {
    "id": 118,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Đường ĐT 744: trước Công ty TNHH Nhạc cụ Quang Hợp",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.122,
    "lng": 106.535,
    "note": "6 điểm ngập cục bộ trên ĐT 744"
  },
  {
    "id": 119,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Đường ĐT 744: trước cửa hàng xăng dầu Hồ Bửu",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.126,
    "lng": 106.531,
    "note": "6 điểm ngập cục bộ trên ĐT 744"
  },
  {
    "id": 120,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Bến Cát",
    "street": "Đường ĐT 744: trước Công ty CP Bê tông Thủ Đức",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Điểm ngập cục bộ",
    "lat": 11.13,
    "lng": 106.527,
    "note": "6 điểm ngập cục bộ trên ĐT 744"
  },
  {
    "id": 121,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thủ Dầu Một",
    "street": "ngã ba Cống, đường Thích Quảng Đức",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.975,
    "lng": 106.666,
    "note": "Ngập do mưa và triều (Thủ Dầu Một)"
  },
  {
    "id": 122,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thủ Dầu Một",
    "street": "đường ven rạch Bưng Cải",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.972,
    "lng": 106.658,
    "note": "Ngập do mưa và triều (Thủ Dầu Một)"
  },
  {
    "id": 123,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thủ Dầu Một",
    "street": "đường Hồ Văn Cống",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.963,
    "lng": 106.651,
    "note": "Ngập do mưa và triều (Thủ Dầu Một)"
  },
  {
    "id": 124,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "khu vực suối Bình Thắng",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.884,
    "lng": 106.786,
    "note": "Ngập do mưa và triều (Dĩ An)"
  },
  {
    "id": 125,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Dĩ An",
    "street": "Quốc lộ 1K đoạn từ khu vực dốc Chú Hỏa đến rạch Cái Cầu",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.882,
    "lng": 106.793,
    "note": "Ngập do mưa và triều (Dĩ An)"
  },
  {
    "id": 126,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đại lộ Bình Dương (Quốc lộ 13) đoạn trước Công ty TNHH Dịch vụ Thương mại Tân Hiệp Phát",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.912,
    "lng": 106.713,
    "note": "Ngập do mưa và triều (Thuận An)"
  },
  {
    "id": 127,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đại lộ Bình Dương (Quốc lộ 13) đoạn trước Công ty Fito",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.908,
    "lng": 106.716,
    "note": "Ngập do mưa và triều (Thuận An)"
  },
  {
    "id": 128,
    "region": "binh-duong",
    "regionName": "Bình Dương",
    "ward": "Thành phố Thuận An",
    "street": "đường Cách Mạng Tháng 8 đoạn cống ngang Cầu Nhỏ",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.916,
    "lng": 106.697,
    "note": "Ngập do mưa và triều (Thuận An)"
  },
  {
    "id": 129,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Tam Thắng",
    "street": "đường Thi Sách",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.354,
    "lng": 107.086,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 130,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Tam Thắng",
    "street": "đường Nguyễn Đình Thi",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.356,
    "lng": 107.088,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 131,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Tam Thắng",
    "street": "ngã ba Quang Trung - Hạ Long",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.347,
    "lng": 107.072,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 132,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Vũng Tàu",
    "street": "đường Nguyễn Du",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.349,
    "lng": 107.076,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 133,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Vũng Tàu",
    "street": "đường Trưng Trắc - Trưng Nhị",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.348,
    "lng": 107.074,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 134,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Vũng Tàu",
    "street": "đường Lê Lợi tại ngã ba Lê Hồng Phong",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.358,
    "lng": 107.078,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 135,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phú Mỹ",
    "street": "đường Nguyễn Tất Thành",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.592,
    "lng": 107.048,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 136,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phú Mỹ",
    "street": "đường Lê Lợi",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.595,
    "lng": 107.051,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 137,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phú Mỹ",
    "street": "đường Nguyễn Trãi",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.59,
    "lng": 107.046,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 138,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phú Mỹ",
    "street": "Quốc lộ 51 giao với đường Huỳnh Thúc Kháng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.598,
    "lng": 107.044,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 139,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phú Mỹ",
    "street": "Quốc lộ 51 giao với đường Lê Duẩn",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.601,
    "lng": 107.042,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 140,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phú Mỹ",
    "street": "Quốc lộ 51 giao với đường Phạm Văn Đồng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.604,
    "lng": 107.04,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 141,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phú Mỹ",
    "street": "Quốc lộ 51 đoạn trước chung cư Hodeco - khu vực Miếu Cô Mai và từ ngã ba Mỹ Xuân đến ngã tư Mỹ Xuân B1",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.612,
    "lng": 107.035,
    "note": "Ngập nặng, thường xuyên trên QL51"
  },
  {
    "id": 142,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phước Thắng",
    "street": "đường Võ Nguyên Giáp",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "severe",
    "severityName": "Ngập nặng, thường xuyên",
    "lat": 10.402,
    "lng": 107.124,
    "note": "Ngập nặng, thường xuyên"
  },
  {
    "id": 143,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Tam Thắng",
    "street": "đường Nguyễn Quyền",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.357,
    "lng": 107.084,
    "note": "Ngập vừa"
  },
  {
    "id": 144,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Vũng Tàu",
    "street": "hẻm 99 đường Trương Công Định",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.354,
    "lng": 107.079,
    "note": "Ngập vừa"
  },
  {
    "id": 145,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phú Mỹ",
    "street": "đường Mỹ Xuân B1",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.618,
    "lng": 107.041,
    "note": "Ngập vừa"
  },
  {
    "id": 146,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Tân Thành",
    "street": "đường Nguyễn Hữu Tiến",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.584,
    "lng": 107.056,
    "note": "Ngập vừa"
  },
  {
    "id": 147,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Xã Long Hải",
    "street": "đường Nguyễn Lương Bằng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.379,
    "lng": 107.242,
    "note": "Ngập vừa"
  },
  {
    "id": 148,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Phước Thắng",
    "street": "hẻm 1 Trần Xuân Độ - 115 Lê Lợi",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.395,
    "lng": 107.112,
    "note": "Ngập vừa"
  },
  {
    "id": 149,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Rạch Dừa",
    "street": "đường 30/4 đoạn từ đường Lê Quang Định đến đường Nguyễn Hữu Cảnh",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.384,
    "lng": 107.108,
    "note": "Ngập vừa"
  },
  {
    "id": 150,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Rạch Dừa",
    "street": "đường 2/9 đoạn từ đường Lê Quang Định đến số 442 Bình Giã",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.387,
    "lng": 107.112,
    "note": "Ngập vừa"
  },
  {
    "id": 151,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Bà Rịa",
    "street": "đường Cách Mạng Tháng 8: từ ngã tư Tôn Đức Thắng đến ngã tư Nguyễn Tất Thành",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.498,
    "lng": 107.168,
    "note": "CMT8 gồm 3 đoạn"
  },
  {
    "id": 152,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Bà Rịa",
    "street": "đường Cách Mạng Tháng 8: ngã tư Cách Mạng Tháng 8 - Phạm Văn Đồng",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.495,
    "lng": 107.171,
    "note": "CMT8 gồm 3 đoạn"
  },
  {
    "id": 153,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Bà Rịa",
    "street": "đường Cách Mạng Tháng 8: ngã tư Trần Phú - Võ Văn Kiệt",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.492,
    "lng": 107.175,
    "note": "CMT8 gồm 3 đoạn"
  },
  {
    "id": 154,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Phường Hắc Dịch",
    "street": "khu tái định cư",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "moderate",
    "severityName": "Ngập vừa",
    "lat": 10.638,
    "lng": 107.128,
    "note": "Khu tái định cư Hắc Dịch (Ngập vừa)"
  },
  {
    "id": 155,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Xã Long Điền",
    "street": "đường Nguyễn Tất Thành, đoạn giao với đường Hùng Vương",
    "cause": "rain",
    "causeName": "Ngập do mưa",
    "severity": "light",
    "severityName": "Ngập nhẹ",
    "lat": 10.428,
    "lng": 107.198,
    "note": "Ngập nhẹ"
  },
  {
    "id": 156,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Thành phố Vũng Tàu",
    "street": "khu Decoimex mở rộng",
    "cause": "tide",
    "causeName": "Ngập do triều",
    "severity": "tide",
    "severityName": "Ngập do triều",
    "lat": 10.372,
    "lng": 107.098,
    "note": "1 vị trí tại khu Decoimex mở rộng"
  },
  {
    "id": 157,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Thành phố Vũng Tàu",
    "street": "khu Decoimex mở rộng (phường 9)",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.374,
    "lng": 107.096,
    "note": "Khu Decoimex mở rộng thuộc phường 9"
  },
  {
    "id": 158,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Thành phố Vũng Tàu",
    "street": "hẻm 646 đường 30/4",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.381,
    "lng": 107.104,
    "note": "Hẻm 646 đường 30/4"
  },
  {
    "id": 159,
    "region": "vung-tau",
    "regionName": "Bà Rịa - Vũng Tàu",
    "ward": "Thành phố Vũng Tàu",
    "street": "cuối hẻm 842 đường Bình Giã",
    "cause": "rain-tide",
    "causeName": "Ngập do mưa và triều",
    "severity": "severe",
    "severityName": "Mưa & triều",
    "lat": 10.384,
    "lng": 107.107,
    "note": "Cuối hẻm 842 đường Bình Giã"
  }
];
